controller_manager:
  ros__parameters:
    use_sim_time: False
    update_rate: 1000	  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

    interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 200.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.01
      joint1:
        goal_position: 0.01
      joint2:
        goal_position: 0.01
      joint3:
        goal_position: 0.01
      joint4:
        goal_position: 0.01
      joint5:
        goal_position: 0.01
      joint6:
        goal_position: 0.01
      joint7:
        goal_position: 0.01

